'use client'
import { useEffect, useState } from 'react'
import { Check, Clock3, Users, ArrowUpRight, UserRound } from 'lucide-react'
import { supabase } from '@/lib/supabase'

const demo = [{ id:'SF-24810', type:'Garbage', area:'Central market', status:'pending', assigned_worker_id:'' }, { id:'SF-24811', type:'Water leakage', area:'Ward 4', status:'in_progress', assigned_worker_id:'' }, { id:'SF-24812', type:'Pothole', area:'Main road', status:'resolved', assigned_worker_id:'' }]

type Worker = { id:string; name:string; assigned_area:string | null }
type Complaint = { id:string; waste_type:string; status:string; location_lat:number | null; location_lng:number | null; assigned_worker_id:string | null; created_at?:string }

export default function Admin() {
  const [rows, setRows] = useState<Complaint[]>(demo as Complaint[])
  const [workers, setWorkers] = useState<Worker[]>([])
  const [message, setMessage] = useState('')
  useEffect(() => { const load = async () => { if (!supabase) return; const [{ data: complaints }, { data: team }] = await Promise.all([supabase.from('complaints').select('*').order('created_at', { ascending:false }), supabase.from('workers').select('id,name,assigned_area').order('name')]); if (complaints?.length) setRows(complaints); if (team) setWorkers(team) }; load() }, [])
  const updateStatus = async (id:string, status:string) => { setRows(r => r.map(x => x.id === id ? {...x, status} : x)); const result = await supabase?.from('complaints').update({status}).eq('id', id); if (result?.error) setMessage(result.error.message) }
  const assign = async (id:string, workerId:string) => { setRows(r => r.map(x => x.id === id ? {...x, assigned_worker_id: workerId || null} : x)); const result = await supabase?.from('complaints').update({assigned_worker_id: workerId || null, status: workerId ? 'in_progress' : 'pending'}).eq('id', id); if (result?.error) setMessage(result.error.message); else setMessage(workerId ? 'Complaint assigned and moved to In Progress.' : 'Worker assignment removed.') }
  return <div className="mx-auto max-w-7xl px-6 py-12 lg:px-10"><div className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-gold">Operations desk</p><h1 className="mt-3 text-5xl">Authority panel</h1></div><span className="hidden items-center gap-2 text-xs text-navy/50 md:flex"><span className="h-2 w-2 rounded-full bg-green-700"/>System operational</span></div><div className="mt-10 grid gap-4 md:grid-cols-3"><Metric icon={Clock3} n={String(rows.filter(r=>r.status==='pending').length)} l="Pending reports"/><Metric icon={Users} n={String(workers.length || 14)} l="Active workers"/><Metric icon={Check} n={`${rows.length ? Math.round(rows.filter(r=>r.status==='resolved').length / rows.length * 100) : 0}%`} l="Resolution rate"/></div>{message && <p className="mt-5 rounded-xl bg-gold/10 p-4 text-sm text-navy">{message}</p>}<div className="mt-10 overflow-hidden rounded-2xl border border-gold/20 bg-white/50 shadow-luxury"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-gold/20 bg-navy text-xs uppercase tracking-widest text-ivory/70"><tr><th className="p-5">Reference</th><th>Issue</th><th>Location</th><th>Status</th><th>Assign worker</th><th className="p-5">Update</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b border-gold/10 last:border-0"><td className="p-5 font-mono text-xs text-gold">#{String(r.id).slice(0,10)}</td><td className="font-semibold">{r.waste_type}</td><td className="text-navy/55">{r.location_lat ? `${Number(r.location_lat).toFixed(3)}, ${Number(r.location_lng).toFixed(3)}` : 'Reported location'}</td><td><span className="rounded-full bg-mist px-3 py-1 text-xs capitalize">{r.status.replace('_',' ')}</span></td><td><div className="flex items-center gap-2"><UserRound size={15} className="text-gold"/><select value={r.assigned_worker_id || ''} onChange={e => assign(r.id, e.target.value)} className="rounded-lg border border-gold/30 bg-ivory px-3 py-2 text-xs"><option value="">Unassigned</option>{workers.map(w => <option key={w.id} value={w.id}>{w.name}{w.assigned_area ? ` · ${w.assigned_area}` : ''}</option>)}</select></div></td><td className="p-5"><select value={r.status} onChange={e => updateStatus(r.id, e.target.value)} className="rounded-lg border border-gold/30 bg-ivory px-3 py-2 text-xs"><option value="pending">Pending</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option></select></td></tr>)}</tbody></table></div></div><p className="mt-5 flex items-center gap-2 text-xs text-navy/45"><ArrowUpRight size={14}/> Assignments sync with the worker workspace.</p></div>
}
function Metric({icon:Icon,n,l}:{icon:any;n:string;l:string}) { return <div className="glass rounded-2xl p-6 shadow-luxury"><Icon size={19} className="text-gold"/><p className="serif mt-5 text-4xl">{n}</p><p className="mt-1 text-xs uppercase tracking-widest text-navy/50">{l}</p></div> }
